Kareem/swpy 1079 simplify the call to log error
SoftwearDevelopment/spynl pull request #12
Opened 2017-03-16 14:26 UTC by Kareeeeem

2017-03-17 09:23 UTC, RosanneZe reviewed
I thought that you were going to add the optional debug message in this ticket as well? Do you want to do that in a new ticket? Otherwise, nice cleanup.

2017-03-17 09:23 UTC, RosanneZe commented on spynl/main/utils.py
> +        error_type = error_type[:-len('Exception')]
I would be ok with removing these two lines, maybe someone else would like to chime in? (removing Exception from the error type) Do we do this for a reason?

2017-03-17 09:23 UTC, RosanneZe commented on spynl/tests/test_log_error.py
> +    """Patch a number of things so we can return a logger and not have any
In multiline docstrings both the top and bottom """ should have their own line.

2017-03-17 09:24 UTC, Kareeeeem commented on spynl/tests/test_log_error.py
> +    """Patch a number of things so we can return a logger and not have any
I really need to install that pydocstyle thing because I gotta break a habit for this :)

2017-03-17 10:37 UTC, Kareeeeem commented
Yea I forgot about the debug_message being the thing that sparked the idea to clean this up. It is included now.

2017-03-17 11:52 UTC, RosanneZe requested changes
If you get it to work with the debug message in the init, could you also add a comment in spynl.main.exceptions.SpynlException that explains how to add a debug message?

2017-03-17 11:52 UTC, RosanneZe commented on spynl/tests/test_log_error.py
> +
My idea was to implement it like this:
```python
class SomeException(Exception):
        def __init__(self):
            self.debug_message = 'Debug this.'
```

I tested it, and it doesn't seem to work this way. (This way the message and the debug message will be together)

2017-03-20 12:52 UTC, Kareeeeem commented on spynl/main/utils.py
> +        error_type = error_type[:-len('Exception')]
Not sure honestly, it was there and I left it. Agree that there isn't much point.

2017-03-20 12:56 UTC, RosanneZe approved these changes

2017-03-21 09:25 UTC, bobbydams commented
approved, but should be rebased and merged

2017-03-21 09:26 UTC, o-m-n-i reviewed
looks good to me

2017-03-21 12:17 UTC, closed without merging

2017-03-21 12:30 UTC, Kareeeeem commented
forgot to force push, was merged.