SPAPI-43 expose a developer message in the api
SoftwearDevelopment/spynl pull request #19
Opened 2017-04-25 09:07 UTC by Kareeeeem

2017-04-28 07:27 UTC, RosanneZe requested changes
Looks good, but because we now have quite a few messages, I think we should be very explicit about what they are for. Maybe we can even repeat some of this info in make_response, but that might be a bit too much?

2017-04-28 07:27 UTC, RosanneZe commented on spynl/main/exceptions.py
>          self.message = message
I think here we need a few short comments:
```python
# friendly message for the end user, exposed, should not contain sensitive information
self.message = message
# debug message for internal use
self.debug_message = debug_message or self.message
# developer message for external programmers that use the Spynl API, exposed, should not contain sensitive information
self.developer_message = developer_message or self.message
```

2017-04-28 07:40 UTC, ev-agelos commented on spynl/main/exceptions.py
>          self.message = message
Sure but I would put them in the docstring of the __init__ method.
Other than that PR seems fine by me.

2017-04-28 07:40 UTC, ev-agelos approved these changes

2017-05-01 07:31 UTC, o-m-n-i reviewed
I think exposing a developer friendly message is nice, not sure about the debug message though. You could accidentally expose sensitive information if somehow the debug flag gets set in a production environment. Curious to know what @koraa thinks.

2017-05-01 07:41 UTC, Kareeeeem commented on spynl/main/exceptions.py
>          self.message = message
Will put them in the docstring.

2017-05-01 07:41 UTC, Kareeeeem commented
The debug message was there before. It is also never sent in the response, it is used for logging. https://github.com/SoftwearDevelopment/spynl/blob/kareem/SPAPI-43/spynl/main/utils.py#L472

2017-05-01 11:19 UTC, koraa commented
@Kareeeeem Precisely

2017-05-01 11:21 UTC, bobbydams commented
@Kareeeeem okay perfect. Then I'm fine with the changes +1

2017-05-01 11:21 UTC, o-m-n-i approved these changes

2017-05-01 11:22 UTC, koraa commented
I just looked over the code again, and I am wondering: Do we have any 3pty users using our API?

2017-05-01 12:11 UTC, RosanneZe approved these changes

2017-05-01 12:18 UTC, closed without merging

2017-05-01 12:19 UTC, Kareeeeem commented
forgot to force push before deleting the branch. it is merged.

2017-05-01 12:20 UTC, Kareeeeem commented
@koraa there will be soon. I remebber @bobbydams telling us about a meeting he was in last week that was about 3rd party users.